{
 "title": "Sample Dashboard",
 "tags": [
  "prometheus",
  ".net core",
  "grafana"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Heap Size & GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum(system_runtime_gen_0_size)", "legendFormat": "Gen 0" },
    { "expr": "sum(system_runtime_gen_1_size)", "legendFormat": "Gen 1" },
    { "expr": "sum(system_runtime_gen_2_size)", "legendFormat": "Gen 2 {{pod}}" },
    { "expr": "sum(system_runtime_loh_size)", "legendFormat": "LOH" },
    { "expr": "sum(system_runtime_poh_size)", "legendFormat": "POH" },
    {
     "expr": "sum(system_runtime_gen_0_gc_count_total * 120)",
     "legendFormat": "Count Gen 0"
    },
    {
     "expr": "sum(system_runtime_gen_1_gc_count_total * 120)",
     "legendFormat": "Count Gen 1"
    },
    {
     "expr": "sum(system_runtime_gen_2_gc_count_total * 120)",
     "legendFormat": "Count Gen 2"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_num_threads) by (instance)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time in GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_runtime_time_in_gc", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_handles) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Exception count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_runtime_exception_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The duration of HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_in_progress) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}